/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BuyMeAChocolateABI__factory } from "./BuyMeAChocolateABI__factory";
export { ERC20ABI__factory } from "./ERC20ABI__factory";
